name: Actualizar Canales TV

on:
  schedule:
    - cron: '*/30 * * * *' # Ejecutar cada 30 min
  workflow_dispatch: # Botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Bajar código
        uses: actions/checkout@v4 # Actualizado a v4
        with:
          fetch-depth: 0 # Trae todo el historial para evitar conflictos de rama

      - name: Instalar Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests

      - name: Correr el Scraper
        run: python scraper.py

      # Sincronizamos por si hubo cambios manuales en el repo mientras corría el scraper
      - name: Pull de cambios remotos
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase

      - name: Guardar cambios (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v5 # Actualizado a v5
        with:
          commit_message: "Actualizacion Automatica de Links"
          file_pattern: 'canales.json'
          branch: main
